[global]
interval_s = 60
output = "data/readings.csv"
utc = true

[[devices]]
id = "hrc110-eth"
type = "hrc110"
transport = "tcp"
host = "192.168.0.187"
port = 4266
# read_terminators = ["\r\n"]
query = "MEAS? 2"

[[devices]]
id = "scm10-eth"
type = "scm10"
transport = "tcp"
host = "192.168.0.4"
port = 9760

[[devices]]
id = "cpa1114-eth"
type = "cpa1114"
transport = "tcp"
host = "192.168.0.111"
port = 502
# unit_id = 16
